// ════════════════════════════════════════════════════════
//  VISASPRO — MAPPINGS.JS  v2.0
//  Fuente: Definiciones_Extension_VisasPro_-_AutoFiller.xlsx
// ════════════════════════════════════════════════════════

// ── Funciones de limpieza ────────────────────────────────

const CLEAN = {

  // Quita acentos, caracteres no-ASCII y especiales. Solo letras, números y espacios. MAYÚSCULAS.
  text: (val) => (val || '')
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^\x00-\x7F]/g, '')
    .replace(/[^A-Z0-9 ]/gi, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toUpperCase(),

  // Solo minúsculas — único campo que NO va a mayúsculas
  email: (val) => (val || '')
    .trim()
    .toLowerCase(),

  // Solo dígitos, máximo 10
  phone: (val) => (val || '')
    .trim()
    .replace(/[^\d]/g, '')
    .slice(0, 10),

  // Solo dígitos, máximo 5
  zip: (val) => (val || '')
    .trim()
    .replace(/[^\d]/g, '')
    .slice(0, 5),

  // Solo los últimos 8 dígitos (de derecha a izquierda)
  visa: (val) => (val || '')
    .trim()
    .replace(/[^\d]/g, '')
    .slice(-8),
};


// ── Tablas de equivalencia ───────────────────────────────

const EQUIV = {

  gender: {
    'Masculino': 'M',
    'Femenino':  'F',
  },

  maritalStatus: {
    'Casado(a)':                              'M',
    'Union libre':                            'C',
    'Union civil/Vida conyugal':              'P',
    'Soltero(a)':                             'S',
    'Viudo(a)':                               'W',
    'Divorciado(a)':                          'D',
    'Legalmente separado(a) de su conyuge':   'L',
    'Otro':                                   'O',
  },

  month: {
    'Enero':      'JAN',
    'Febrero':    'FEB',
    'Marzo':      'MAR',
    'Abril':      'APR',
    'Mayo':       'MAY',
    'Junio':      'JUN',
    'Julio':      'JUL',
    'Agosto':     'AUG',
    'Septiembre': 'SEP',
    'Octubre':    'OCT',
    'Noviembre':  'NOV',
    'Diciembre':  'DEC',
  },

  // País/región de nacimiento — estados de México + resto del mundo
  paisRegion: {
    'Mexico - Aguascalientes':      'AGS',
    'Mexico - Baja California':     'BC',
    'Mexico - Baja California Sur': 'BCSR',
    'Mexico - Campeche':            'CAMP',
    'Mexico - Chiapas':             'CHIS',
    'Mexico - Chihuahua':           'CHIH',
    'Mexico - Coahuila':            'COAH',
    'Mexico - Colima':              'COLI',
    'Mexico - Distrito Federal':    'DF',
    'Mexico - Ciudad de Mexico':    'DF',
    'Mexico - Durango':             'DGO',
    'Mexico - Guanajuato':          'GTO',
    'Mexico - Guerrero':            'GRO',
    'Mexico - Hidalgo':             'HGO',
    'Mexico - Jalisco':             'JAL',
    'Mexico - Michoacan':           'MCH',
    'Mexico - Morelos':             'MOR',
    'Mexico - Nayarit':             'NAY',
    'Mexico - Nuevo Leon':          'NL',
    'Mexico - Oaxaca':              'OAX',
    'Mexico - Puebla':              'PUE',
    'Mexico - Queretaro':           'QRO',
    'Mexico - Quintana Roo':        'QROO',
    'Mexico - San Luis Potosi':     'SLP',
    'Mexico - Sinaloa':             'SIN',
    'Mexico - Sonora':              'SON',
    'Mexico - Estado de Mexico':    'MXCO',
    'Mexico - Tabasco':             'TAB',
    'Mexico - Tamaulipas':          'TAMP',
    'Mexico - Tlaxcala':            'TLAX',
    'Mexico - Veracruz':            'VER',
    'Mexico - Yucatan':             'YUC',
    'Mexico - Zacatecas':           'ZAC',
    'AFGANISTAN':                   'AFGH',
    'ALBANIA':                      'ALB',
    'ALEMANIA':                     'GER',
    'ANDORRA':                      'ANDO',
    'ANGOLA':                       'ANGL',
    'ANGUILA':                      'ANGU',
    'ANTIGUA Y BARBUDA':            'ANTI',
    'ARABIA SAUDITA':               'SARB',
    'ARGELIA':                      'ALGR',
    'ARGENTINA':                    'ARG',
    'ARMENIA':                      'ARM',
    'ARUBA':                        'ARB',
    'ATOLON PALMYRA':               'PLMR',
    'AUSTRALIA':                    'ASTL',
    'AUSTRIA':                      'AUST',
    'AZERBAIYAN':                   'AZR',
    'BAHAMAS':                      'BAMA',
    'BANGLADES':                    'BANG',
    'BARBADOS':                     'BRDO',
    'BAREIN':                       'BAHR',
    'BELGICA':                      'BELG',
    'BELICE':                       'BLZ',
    'BENIN':                        'BENN',
    'BERMUDAS':                     'BERM',
    'BIELORRUSIA':                  'BYS',
    'BIRMANIA':                     'BURM',
    'BOLIVIA':                      'BOL',
    'BONAIRE':                      'BON',
    'BOSNIA-HERZEGOVINA':           'BIH',
    'BOTSUANA':                     'BOT',
    'BRASIL':                       'BRZL',
    'BRUNEI':                       'BRNI',
    'BULGARIA':                     'BULG',
    'BURKINA FASO':                 'BURK',
    'BURUNDI':                      'BRND',
    'BUTAN':                        'BHU',
    'CABO VERDE':                   'CAVI',
    'CAMBOYA':                      'CBDA',
    'CAMERUN':                      'CMRN',
    'CANADA':                       'CAN',
    'CATAR':                        'QTAR',
    'CHAD':                         'CHAD',
    'CHILE':                        'CHIL',
    'CHINA':                        'CHIN',
    'CHIPRE':                       'CYPR',
    'CISJORDANIA':                  'XWB',
    'COLOMBIA':                     'COL',
    'COMORAS':                      'COMO',
    'CONGO REPUBLICA DEL':          'CONB',
    'CONGO REPUBLICA DEMOCRATICA DEL': 'COD',
    'COREA REPUBLICA DE SUR':       'KOR',
    'COREA REPUBLICA DEMOCRATICA DE NORTE': 'PRK',
    'COSTA DE MARFIL':              'IVCO',
    'COSTA RICA':                   'CSTR',
    'CROACIA':                      'HRV',
    'CUBA':                         'CUBA',
    'CURAZAO':                      'CUR',
    'DINAMARCA':                    'DEN',
    'DOMINICA':                     'DOMN',
    'ECUADOR':                      'ECUA',
    'EGIPTO':                       'EGYP',
    'EL SALVADOR':                  'ELSL',
    'EMIRATOS ARABES UNIDOS':       'UAE',
    'ERITREA':                      'ERI',
    'ESLOVAQUIA':                   'SVK',
    'ESLOVENIA':                    'SVN',
    'ESPANA':                       'SPN',
    'ESTONIA':                      'EST',
    'ESUATINI':                     'SZLD',
    'ETIOPIA':                      'ETH',
    'FILIPINAS':                    'PHIL',
    'FINLANDIA':                    'FIN',
    'FIYI':                         'FIJI',
    'FRANCIA':                      'FRAN',
    'FRANJA DE GAZA':               'XGZ',
    'GABON':                        'GABN',
    'GAMBIA':                       'GAM',
    'GEORGIA':                      'GEO',
    'GEORGIA DEL SUR E ISLAS SANDWICH DEL SUR': 'SGS',
    'GHANA':                        'GHAN',
    'GIBRALTAR':                    'GIB',
    'GRANADA':                      'GREN',
    'GRECIA':                       'GRC',
    'GROENLANDIA':                  'GRLD',
    'GUADALUPE':                    'GUAD',
    'GUAM':                         'GUAM',
    'GUATEMALA':                    'GUAT',
    'GUAYANA FRANCESA':             'FRGN',
    'GUINEA':                       'GNEA',
    'GUINEA ECUATORIAL':            'EGN',
    'GUINEA BISAU':                 'GUIB',
    'GUYANA':                       'GUY',
    'HAITI':                        'HAT',
    'HONDURAS':                     'HOND',
    'HONG KONG':                    'HNK',
    'HUNGRIA':                      'HUNG',
    'INDIA':                        'IND',
    'INDONESIA':                    'IDSA',
    'IRAK':                         'IRAQ',
    'IRAN':                         'IRAN',
    'IRLANDA':                      'IRE',
    'IRLANDA DEL NORTE':            'NIRE',
    'ISLA DE NAVIDAD':              'CHRI',
    'ISLA HOWLAND':                 'XHI',
    'ISLA MALDEN':                  'MLDI',
    'ISLA NORFOLK':                 'NFK',
    'ISLA SABA':                    'SABA',
    'ISLA WAKE':                    'WKI',
    'ISLANDIA':                     'ICLD',
    'ISLAS CAIMAN':                 'CAYI',
    'ISLAS COCOS':                  'COCI',
    'ISLAS COOK':                   'CKIS',
    'ISLAS FEROE':                  'FRO',
    'ISLAS HEARD Y MCDONALD':       'HMD',
    'ISLAS MALVINAS':               'FKLI',
    'ISLAS MARIANAS DEL NORTE':     'MNP',
    'ISLAS MARSHALL':               'RMI',
    'ISLAS MIDWAY':                 'MDWI',
    'ISLAS PITCAIRN':               'PITC',
    'ISLAS SALOMON':                'SLMN',
    'ISLAS TURCAS Y CAICOS':        'TCIS',
    'ISLAS VIRGENES EE UU':         'VI',
    'ISLAS VIRGENES BRITANICAS':    'BRVI',
    'ISLAS WALLIS Y FUTUNA':        'WAFT',
    'ISRAEL':                       'ISRL',
    'ITALIA':                       'ITLY',
    'JAMAICA':                      'JAM',
    'JAPON':                        'JPN',
    'JERUSALEN':                    'JRSM',
    'JORDANIA':                     'JORD',
    'KAZAJISTAN':                   'KAZ',
    'KENIA':                        'KENY',
    'KIRGUISTAN':                   'KGZ',
    'KIRIBATI':                     'KIRI',
    'KOSOVO':                       'KSV',
    'KUWAIT':                       'KUWT',
    'LAOS':                         'LAOS',
    'LESOTO':                       'LES',
    'LETONIA':                      'LATV',
    'LIBANO':                       'LEBN',
    'LIBERIA':                      'LIBR',
    'LIBIA':                        'LBYA',
    'LIECHTENSTEIN':                'LCHT',
    'LITUANIA':                     'LITH',
    'LUXEMBURGO':                   'LXM',
    'MACAO':                        'MAC',
    'MACEDONIA DEL NORTE':          'MKD',
    'MADAGASCAR':                   'MADG',
    'MALASIA':                      'MLAS',
    'MALAUI':                       'MALW',
    'MALDIVAS':                     'MLDV',
    'MALI':                         'MALI',
    'MALTA':                        'MLTA',
    'MARRUECOS':                    'MORO',
    'MARTINICA':                    'MART',
    'MAURICIO':                     'MRTS',
    'MAURITANIA':                   'MAUR',
    'MAYOTTE':                      'MYT',
    'MICRONESIA':                   'FSM',
    'MOLDAVIA':                     'MLD',
    'MONACO':                       'MON',
    'MONGOLIA':                     'MONG',
    'MONTENEGRO':                   'MTG',
    'MONTSERRAT':                   'MONT',
    'MOZAMBIQUE':                   'MOZ',
    'NAMIBIA':                      'NAMB',
    'NAURU':                        'NAU',
    'NEPAL':                        'NEP',
    'NICARAGUA':                    'NIC',
    'NIGER':                        'NIR',
    'NIGERIA':                      'NRA',
    'NIUE':                         'NIUE',
    'NORUEGA':                      'NORW',
    'NUEVA CALEDONIA':              'NCAL',
    'NUEVA ZELANDA':                'NZLD',
    'OMAN':                         'OMAN',
    'PAISES BAJOS':                 'NETH',
    'PAKISTAN':                     'PKST',
    'PALAOS':                       'PALA',
    'PANAMA':                       'PAN',
    'PAPUA NUEVA GUINEA':           'PNG',
    'PARAGUAY':                     'PARA',
    'PERU':                         'PERU',
    'POLINESIA FRANCESA':           'FPOL',
    'POLONIA':                      'POL',
    'PORTUGAL':                     'PORT',
    'PUERTO RICO':                  'PR',
    'REINO UNIDO':                  'GRBR',
    'REPUBLICA CENTROAFRICANA':     'CAFR',
    'REPUBLICA CHECA':              'CZEC',
    'REPUBLICA DOMINICANA':         'DOMR',
    'REUNION':                      'REUN',
    'RUANDA':                       'RWND',
    'RUMANIA':                      'ROM',
    'RUSIA':                        'RUS',
    'SAHARA OCCIDENTAL':            'SSAH',
    'SAINT MARTIN':                 'MAF',
    'SAMOA':                        'WSAM',
    'SAMOA AMERICANA':              'ASMO',
    'SAN CRISTOBAL Y NIEVES':       'STCN',
    'SAN EUSTAQUIO':                'STEU',
    'SAN MARINO':                   'SMAR',
    'SAN PEDRO Y MIQUELON':         'SPMI',
    'SAN VICENTE Y LAS GRANADINAS': 'STVN',
    'SANTA ELENA':                  'SHEL',
    'SANTA LUCIA':                  'SLCA',
    'SANTA SEDE CIUDAD DEL VATICANO': 'VAT',
    'SANTO TOME Y PRINCIPE':        'STPR',
    'SENEGAL':                      'SENG',
    'SERBIA':                       'SBA',
    'SEYCHELLES':                   'SEYC',
    'SIERRA LEONA':                 'SLEO',
    'SINGAPUR':                     'SING',
    'SINT MAARTEN':                 'STM',
    'SIRIA':                        'SYR',
    'SOMALIA':                      'SOMA',
    'SRI LANKA':                    'SRL',
    'SUDAFRICA':                    'SAFR',
    'SUDAN':                        'SUDA',
    'SUDAN DEL SUR':                'SSDN',
    'SUECIA':                       'SWDN',
    'SUIZA':                        'SWTZ',
    'SURINAM':                      'SURM',
    'SVALBARD':                     'SJM',
    'TAILANDIA':                    'THAI',
    'TAIWAN':                       'TWAN',
    'TANZANIA':                     'TAZN',
    'TAYIKISTAN':                   'TJK',
    'TERRITORIO BRITANICO DEL OCEANO INDICO': 'IOT',
    'TERRITORIOS AUSTRALES Y ANTARTICOS FRANCESES': 'FSAT',
    'TIMOR LESTE':                  'TMOR',
    'TOGO':                         'TOGO',
    'TOKELAU':                      'TKL',
    'TONGA':                        'TONG',
    'TRINIDAD Y TOBAGO':            'TRIN',
    'TUNEZ':                        'TNSA',
    'TURKMENISTAN':                 'TKM',
    'TURQUIA':                      'TRKY',
    'TUVALU':                       'TUV',
    'UCRANIA':                      'UKR',
    'UGANDA':                       'UGAN',
    'URUGUAY':                      'URU',
    'UZBEKISTAN':                   'UZB',
    'VANUATU':                      'VANU',
    'VENEZUELA':                    'VENZ',
    'VIETNAM':                      'VTNM',
    'YEMEN':                        'YEM',
    'YIBUTI':                       'DJI',
    'ZAMBIA':                       'ZAMB',
    'ZIMBABUE':                     'ZIMB',
  },

  travelDurationUnit: {
    'Dia(s)':    'D',
    'Semana(s)': 'W',
    'Mes(es)':   'M',
  },

  // Estados de EUA (hospedaje y contacto)
  usState: {
    'Alabama':        'AL',
    'Alaska':         'AK',
    'Arizona':        'AZ',
    'Arkansas':       'AR',
    'California':     'CA',
    'Colorado':       'CO',
    'Connecticut':    'CT',
    'Delaware':       'DE',
    'Florida':        'FL',
    'Georgia':        'GA',
    'Hawaii':         'HI',
    'Idaho':          'ID',
    'Illinois':       'IL',
    'Indiana':        'IN',
    'Iowa':           'IA',
    'Kansas':         'KS',
    'Kentucky':       'KY',
    'Louisiana':      'LA',
    'Maine':          'ME',
    'Maryland':       'MD',
    'Massachusetts':  'MA',
    'Michigan':       'MI',
    'Minnesota':      'MN',
    'Mississippi':    'MS',
    'Missouri':       'MO',
    'Montana':        'MT',
    'Nebraska':       'NE',
    'Nevada':         'NV',
    'New Hampshire':  'NH',
    'NewHampshire':   'NH',
    'New Jersey':     'NJ',
    'NewJersey':      'NJ',
    'New Mexico':     'NM',
    'NewMexico':      'NM',
    'New York':       'NY',
    'NewYork':        'NY',
    'North Carolina': 'NC',
    'NorthCarolina':  'NC',
    'North Dakota':   'ND',
    'NorthDakota':    'ND',
    'Ohio':           'OH',
    'Oklahoma':       'OK',
    'Oregon':         'OR',
    'Pennsylvania':   'PA',
    'Rhode Island':   'RI',
    'RhodeIsland':    'RI',
    'South Carolina': 'SC',
    'SouthCarolina':  'SC',
    'South Dakota':   'SD',
    'SouthDakota':    'SD',
    'Tennessee':      'TN',
    'Texas':          'TX',
    'Utah':           'UT',
    'Vermont':        'VT',
    'Virginia':       'VA',
    'Washington':     'WA',
    'West Virginia':  'WV',
    'WestVirginia':   'WV',
    'Wisconsin':      'WI',
    'Wyoming':        'WY',
  },

  travelPayer: {
    'Yo mismo':                        'S',
    'Otra Persona':                    'O',
    'Otra compania u organizacion':    'C',
  },

  // Parentesco del pagador del viaje y acompañantes
  payerRelationship: {
    'Hijo(a)':      'C',
    'Padre o Madre':'P',
    'Conyuge':      'S',
    'Otro pariente':'R',
    'Amigo(a)':     'F',
    'Otros':        'O',
  },

  socialMedia: {
    'Facebook':    'FCBK',
    'Google+':     'GOGL',
    'Instagram':   'INST',
    'LinkedIn':    'LINK',
    'MySpace':     'MYSP',
    'Ni una':      'NONE',
    'Pinterest':   'PTST',
    'Reddit':      'RDDT',
    'Twitter (X)': 'TWIT',
  },

  // Parentesco con contacto en EUA
  usContactRelationship: {
    'Pariente':                    'R',
    'Conyuge':                     'S',
    'Amigo(a)':                    'C',
    'Socio de la empresa/negocio': 'B',
    'Empleador':                   'P',
    'Funcionario escolar':         'H',
    'Otros':                       'O',
  },

  // Parentesco familiar en EUA
  usFamilyRelationship: {
    'Conyuge':      'S',
    'Prometido(a)': 'F',
    'Hijo(a)':      'C',
    'Hermano(a)':   'B',
  },

  // Estatus migratorio familiar en EUA
  usStatus: {
    'Ciudadano de los Estados Unidos de Norteamerica':                          'S',
    'Residente Legal Permanente de los Estados Unidos de Norteamerica LPR':    'C',
    'No inmigrante':                                                            'P',
    'Otro/No lo se':                                                            'O',
  },

  occupation: {
    'Empleado':    'O',
    'Estudiante':  'S',
    'Retirado':    'RT',
    'Desempleado': 'N',
    'Otro':        'O',
  },

  // Países (para viajes previos, pasaporte, trabajo anterior)
  countries: {
    'MEXICO':                       'MXN',
    'ESTADOS UNIDOS DE AMERICA':    'USA',
    'AFGANISTAN':                   'AFGH',
    'ALBANIA':                      'ALB',
    'ALEMANIA':                     'GER',
    'ANDORRA':                      'ANDO',
    'ANGOLA':                       'ANGL',
    'ANGUILA':                      'ANGU',
    'ANTIGUA Y BARBUDA':            'ANTI',
    'ARABIA SAUDITA':               'SARB',
    'ARGELIA':                      'ALGR',
    'ARGENTINA':                    'ARG',
    'ARMENIA':                      'ARM',
    'ARUBA':                        'ARB',
    'ATOLON PALMYRA':               'PLMR',
    'AUSTRALIA':                    'ASTL',
    'AUSTRIA':                      'AUST',
    'AZERBAIYAN':                   'AZR',
    'BAHAMAS':                      'BAMA',
    'BANGLADES':                    'BANG',
    'BARBADOS':                     'BRDO',
    'BAREIN':                       'BAHR',
    'BELGICA':                      'BELG',
    'BELICE':                       'BLZ',
    'BENIN':                        'BENN',
    'BERMUDAS':                     'BERM',
    'BIELORRUSIA':                  'BYS',
    'BIRMANIA':                     'BURM',
    'BOLIVIA':                      'BOL',
    'BONAIRE':                      'BON',
    'BOSNIA HERZEGOVINA':           'BIH',
    'BOTSUANA':                     'BOT',
    'BRASIL':                       'BRZL',
    'BRUNEI':                       'BRNI',
    'BULGARIA':                     'BULG',
    'BURKINA FASO':                 'BURK',
    'BURUNDI':                      'BRND',
    'BUTAN':                        'BHU',
    'CABO VERDE':                   'CAVI',
    'CAMBOYA':                      'CBDA',
    'CAMERUN':                      'CMRN',
    'CANADA':                       'CAN',
    'CATAR':                        'QTAR',
    'CHAD':                         'CHAD',
    'CHILE':                        'CHIL',
    'CHINA':                        'CHIN',
    'CHIPRE':                       'CYPR',
    'CISJORDANIA':                  'XWB',
    'COLOMBIA':                     'COL',
    'COMORAS':                      'COMO',
    'CONGO REPUBLICA DEL':          'CONB',
    'CONGO REPUBLICA DEMOCRATICA DEL': 'COD',
    'COREA REPUBLICA DE SUR':       'KOR',
    'COREA REPUBLICA DEMOCRATICA DE NORTE': 'PRK',
    'COSTA DE MARFIL':              'IVCO',
    'COSTA RICA':                   'CSTR',
    'CROACIA':                      'HRV',
    'CUBA':                         'CUBA',
    'CURAZAO':                      'CUR',
    'DINAMARCA':                    'DEN',
    'DOMINICA':                     'DOMN',
    'ECUADOR':                      'ECUA',
    'EGIPTO':                       'EGYP',
    'EL SALVADOR':                  'ELSL',
    'EMIRATOS ARABES UNIDOS':       'UAE',
    'ERITREA':                      'ERI',
    'ESLOVAQUIA':                   'SVK',
    'ESLOVENIA':                    'SVN',
    'ESPANA':                       'SPN',
    'ESTONIA':                      'EST',
    'ESUATINI':                     'SZLD',
    'ETIOPIA':                      'ETH',
    'FILIPINAS':                    'PHIL',
    'FINLANDIA':                    'FIN',
    'FIYI':                         'FIJI',
    'FRANCIA':                      'FRAN',
    'FRANJA DE GAZA':               'XGZ',
    'GABON':                        'GABN',
    'GAMBIA':                       'GAM',
    'GEORGIA':                      'GEO',
    'GEORGIA DEL SUR E ISLAS SANDWICH DEL SUR': 'SGS',
    'GHANA':                        'GHAN',
    'GIBRALTAR':                    'GIB',
    'GRANADA':                      'GREN',
    'GRECIA':                       'GRC',
    'GROENLANDIA':                  'GRLD',
    'GUADALUPE':                    'GUAD',
    'GUAM':                         'GUAM',
    'GUATEMALA':                    'GUAT',
    'GUAYANA FRANCESA':             'FRGN',
    'GUINEA':                       'GNEA',
    'GUINEA ECUATORIAL':            'EGN',
    'GUINEA BISAU':                 'GUIB',
    'GUYANA':                       'GUY',
    'HAITI':                        'HAT',
    'HONDURAS':                     'HOND',
    'HONG KONG':                    'HNK',
    'HUNGRIA':                      'HUNG',
    'INDIA':                        'IND',
    'INDONESIA':                    'IDSA',
    'IRAK':                         'IRAQ',
    'IRAN':                         'IRAN',
    'IRLANDA':                      'IRE',
    'IRLANDA DEL NORTE':            'NIRE',
    'ISLA DE NAVIDAD':              'CHRI',
    'ISLA HOWLAND':                 'XHI',
    'ISLA MALDEN':                  'MLDI',
    'ISLA NORFOLK':                 'NFK',
    'ISLA SABA':                    'SABA',
    'ISLA WAKE':                    'WKI',
    'ISLANDIA':                     'ICLD',
    'ISLAS CAIMAN':                 'CAYI',
    'ISLAS COCOS':                  'COCI',
    'ISLAS COOK':                   'CKIS',
    'ISLAS FEROE':                  'FRO',
    'ISLAS HEARD Y MCDONALD':       'HMD',
    'ISLAS MALVINAS':               'FKLI',
    'ISLAS MARIANAS DEL NORTE':     'MNP',
    'ISLAS MARSHALL':               'RMI',
    'ISLAS MIDWAY':                 'MDWI',
    'ISLAS PITCAIRN':               'PITC',
    'ISLAS SALOMON':                'SLMN',
    'ISLAS TURCAS Y CAICOS':        'TCIS',
    'ISLAS VIRGENES EE UU':         'VI',
    'ISLAS VIRGENES BRITANICAS':    'BRVI',
    'ISLAS WALLIS Y FUTUNA':        'WAFT',
    'ISRAEL':                       'ISRL',
    'ITALIA':                       'ITLY',
    'JAMAICA':                      'JAM',
    'JAPON':                        'JPN',
    'JERUSALEN':                    'JRSM',
    'JORDANIA':                     'JORD',
    'KAZAJISTAN':                   'KAZ',
    'KENIA':                        'KENY',
    'KIRGUISTAN':                   'KGZ',
    'KIRIBATI':                     'KIRI',
    'KOSOVO':                       'KSV',
    'KUWAIT':                       'KUWT',
    'LAOS':                         'LAOS',
    'LESOTO':                       'LES',
    'LETONIA':                      'LATV',
    'LIBANO':                       'LEBN',
    'LIBERIA':                      'LIBR',
    'LIBIA':                        'LBYA',
    'LIECHTENSTEIN':                'LCHT',
    'LITUANIA':                     'LITH',
    'LUXEMBURGO':                   'LXM',
    'MACAO':                        'MAC',
    'MACEDONIA DEL NORTE':          'MKD',
    'MADAGASCAR':                   'MADG',
    'MALASIA':                      'MLAS',
    'MALAUI':                       'MALW',
    'MALDIVAS':                     'MLDV',
    'MALI':                         'MALI',
    'MALTA':                        'MLTA',
    'MARRUECOS':                    'MORO',
    'MARTINICA':                    'MART',
    'MAURICIO':                     'MRTS',
    'MAURITANIA':                   'MAUR',
    'MAYOTTE':                      'MYT',
    'MICRONESIA':                   'FSM',
    'MOLDAVIA':                     'MLD',
    'MONACO':                       'MON',
    'MONGOLIA':                     'MONG',
    'MONTENEGRO':                   'MTG',
    'MONTSERRAT':                   'MONT',
    'MOZAMBIQUE':                   'MOZ',
    'NAMIBIA':                      'NAMB',
    'NAURU':                        'NAU',
    'NEPAL':                        'NEP',
    'NICARAGUA':                    'NIC',
    'NIGER':                        'NIR',
    'NIGERIA':                      'NRA',
    'NIUE':                         'NIUE',
    'NORUEGA':                      'NORW',
    'NUEVA CALEDONIA':              'NCAL',
    'NUEVA ZELANDA':                'NZLD',
    'OMAN':                         'OMAN',
    'PAISES BAJOS':                 'NETH',
    'PAKISTAN':                     'PKST',
    'PALAOS':                       'PALA',
    'PANAMA':                       'PAN',
    'PAPUA NUEVA GUINEA':           'PNG',
    'PARAGUAY':                     'PARA',
    'PERU':                         'PERU',
    'POLINESIA FRANCESA':           'FPOL',
    'POLONIA':                      'POL',
    'PORTUGAL':                     'PORT',
    'PUERTO RICO':                  'PR',
    'REINO UNIDO':                  'GRBR',
    'REPUBLICA CENTROAFRICANA':     'CAFR',
    'REPUBLICA CHECA':              'CZEC',
    'REPUBLICA DOMINICANA':         'DOMR',
    'REUNION':                      'REUN',
    'RUANDA':                       'RWND',
    'RUMANIA':                      'ROM',
    'RUSIA':                        'RUS',
    'SAHARA OCCIDENTAL':            'SSAH',
    'SAINT MARTIN':                 'MAF',
    'SAMOA':                        'WSAM',
    'SAMOA AMERICANA':              'ASMO',
    'SAN CRISTOBAL Y NIEVES':       'STCN',
    'SAN EUSTAQUIO':                'STEU',
    'SAN MARINO':                   'SMAR',
    'SAN PEDRO Y MIQUELON':         'SPMI',
    'SAN VICENTE Y LAS GRANADINAS': 'STVN',
    'SANTA ELENA':                  'SHEL',
    'SANTA LUCIA':                  'SLCA',
    'SANTA SEDE CIUDAD DEL VATICANO': 'VAT',
    'SANTO TOME Y PRINCIPE':        'STPR',
    'SENEGAL':                      'SENG',
    'SERBIA':                       'SBA',
    'SEYCHELLES':                   'SEYC',
    'SIERRA LEONA':                 'SLEO',
    'SINGAPUR':                     'SING',
    'SINT MAARTEN':                 'STM',
    'SIRIA':                        'SYR',
    'SOMALIA':                      'SOMA',
    'SRI LANKA':                    'SRL',
    'SUDAFRICA':                    'SAFR',
    'SUDAN':                        'SUDA',
    'SUDAN DEL SUR':                'SSDN',
    'SUECIA':                       'SWDN',
    'SUIZA':                        'SWTZ',
    'SURINAM':                      'SURM',
    'SVALBARD':                     'SJM',
    'TAILANDIA':                    'THAI',
    'TAIWAN':                       'TWAN',
    'TANZANIA':                     'TAZN',
    'TAYIKISTAN':                   'TJK',
    'TERRITORIO BRITANICO DEL OCEANO INDICO': 'IOT',
    'TERRITORIOS AUSTRALES Y ANTARTICOS FRANCESES': 'FSAT',
    'TIMOR LESTE':                  'TMOR',
    'TOGO':                         'TOGO',
    'TOKELAU':                      'TKL',
    'TONGA':                        'TONG',
    'TRINIDAD Y TOBAGO':            'TRIN',
    'TUNEZ':                        'TNSA',
    'TURKMENISTAN':                 'TKM',
    'TURQUIA':                      'TRKY',
    'TUVALU':                       'TUV',
    'UCRANIA':                      'UKR',
    'UGANDA':                       'UGAN',
    'URUGUAY':                      'URU',
    'UZBEKISTAN':                   'UZB',
    'VANUATU':                      'VANU',
    'VENEZUELA':                    'VENZ',
    'VIETNAM':                      'VTNM',
    'YEMEN':                        'YEM',
    'YIBUTI':                       'DJI',
    'ZAMBIA':                       'ZAMB',
    'ZIMBABUE':                     'ZIMB',
  },

  language: {
    'Espanol':   'SPANISH',
    'Ingles':    'ENGLISH',
    'Frances':   'FRENCH',
    'Aleman':    'GERMAN',
    'Italiano':  'ITALIAN',
    'Portugues': 'PORTUGUESE',
  },

};


// ── Reglas por campo PDF ─────────────────────────────────
//  clean  → función de CLEAN a aplicar
//  equiv  → tabla de EQUIV a usar
//  raw    → sin transformación (pasar tal cual)
//  translate → campo que requiere traducción ES→EN via API

const FIELD_RULES = {

  // ── Información Personal 1 ──
  'PI1_NOMBRE_SOLICITANTE':            { clean: 'text'              },
  'PI1_APELLIDOS_SOLICITANTE':         { clean: 'text'              },
  'PI1_GENERO':                        { equiv: 'gender'            },
  'PI1_ESTADO_CIVIL':                  { equiv: 'maritalStatus'     },
  'PI1_MES_NACIMIENTO_SOLICITANTE':    { equiv: 'month'             },
  'PI1_CIUDAD_NACIMIENTO_SOLICITANTE': { clean: 'text'              },
  'PI1_ESTADO_NACIMIENTO_SOLICITANTE': { clean: 'text'              },
  'PI1_PAIS_REGION_SOLICITANTE':       { equiv: 'paisRegion'        },

  // ── Información Personal 2 ──
  'PI2_CURP':                          { clean: 'text'              },

  // ── Dirección y contacto ──
  'DIR_CALLE':                         { clean: 'text'              },
  'DIR_CIUDAD':                        { clean: 'text'              },
  'DIR_ESTADO':                        { clean: 'text'              },
  'DIR_ZIP':                           { clean: 'zip'               },
  'DIR_CELULAR':                       { clean: 'phone'             },
  'DIR_CORREO':                        { clean: 'email'             },
  'DIR_RRSS':                          { equiv: 'socialMedia'       },
  'DIR_RRSS_USER':                     { raw: true                  },

  // ── Viaje ──
  'TRA_MES_VIAJE':                     { equiv: 'month'             },
  'TRA_DURACION_UNIDAD':               { equiv: 'travelDurationUnit'},
  'TRA_HOSPEDAJE_CALLE':               { clean: 'text'              },
  'TRA_HOSPEDAJE_CIUDAD':              { clean: 'text'              },
  'TRA_HOSPEDAJE_ESTADO':              { equiv: 'usState'           },
  'TRA_HOSPEDAJE_ZIP':                 { clean: 'zip'               },
  'TRA_QUIEN_PAGA_VIAJE':              { equiv: 'travelPayer'       },
  'TRA_PAGA_VIAJE_NOMBRE':             { clean: 'text'              },
  'TRA_PAGA_VIAJE_APELLIDO':           { clean: 'text'              },
  'TRA_PAGA_VIAJE_TELEFONO':           { clean: 'phone'             },
  'TRA_PAGA_VIAJE_PARENTESCO':         { equiv: 'payerRelationship' },
  'TRA_DIRECCION_PAGA_VIAJE_CALLE':    { clean: 'text'              },
  'TRA_DIRECCION_PAGA_VIAJE_CIUDAD':   { clean: 'text'              },
  'TRA_DIRECCION_PAGA_VIAJE_ESTADO':   { clean: 'text'              },
  'TRA_DIRECCION_PAGA_VIAJE_ZIP':      { clean: 'zip'               },

  // ── Acompañantes ──
  'TRA_COM_NOMBRE':                    { clean: 'text'              },
  'TRA_COM_APELLIDO':                  { clean: 'text'              },
  'TRA_COM_PARENTESCO':                { equiv: 'payerRelationship' },

  // ── Viajes previos ──
  'PUST_MES':                          { equiv: 'month'             },
  'PUST_DURACION_UNIDAD':              { equiv: 'travelDurationUnit'},
  'PUST_VISA_PREVIA_E_MES':            { equiv: 'month'             },
  'PUST_VISA_PREVIA_V_MES':            { equiv: 'month'             },
  'PUST_VISA_PREVIA_NUMERO':           { clean: 'visa'              },
  'PUST_EXP_EXTRAVIO':                 { clean: 'text', translate: true },
  'PUST_EXP_RECHAZO':                  { clean: 'text', translate: true },

  // ── Pasaporte ──
  'PAS_NUMBER':                        { clean: 'text'              },
  'PAS_EMISION_CIUDAD':                { clean: 'text'              },
  'PAS_EMISION_ESTADO':                { clean: 'text'              },
  'PAS_EMISION_PAIS':                  { equiv: 'paisRegion'        },
  'PAS_EXP_MES':                       { equiv: 'month'             },
  'PAS_VEN_MES':                       { equiv: 'month'             },
  'PAS_EXTRAVIO_NUM':                  { clean: 'text'              },
  'PAS_EXTRAVIO_EXP':                  { clean: 'text', translate: true },

  // ── Contacto en EUA ──
  'CONTUSA_NOMBRE':                    { clean: 'text'              },
  'CONTUSA_APELLIDO':                  { clean: 'text'              },
  'CONTUSA_HOTEL':                     { clean: 'text'              },
  'CONTAUSA_PARENTESCO':               { equiv: 'usContactRelationship' },
  'CONTAUSA_CALLE':                    { clean: 'text'              },
  'CONTAUSA_CIUDAD':                   { clean: 'text'              },
  'CONTAUSA_ESTADO':                   { equiv: 'usState'           },
  'CONTAUSA_ZIP':                      { clean: 'zip'               },
  'CONTAUSA_TEL':                      { clean: 'phone'             },

  // ── Familia ──
  'FAM_NOMBRE_PADRE':                  { clean: 'text'              },
  'FAM_APELLIDO_PADRE':                { clean: 'text'              },
  'FAM_MES_PADRE':                     { equiv: 'month'             },
  'FAM_NOMBRE_MADRE':                  { clean: 'text'              },
  'FAM_APELLIDO_MADRE':                { clean: 'text'              },
  'FAM_MES_MADRE':                     { equiv: 'month'             },
  'FAM_DIRECTA_NOMBRE':                { clean: 'text'              },
  'FAM_DIRECTA_APELLIDO':              { clean: 'text'              },
  'FAM_DIRECTA_PARENTESCO':            { equiv: 'usFamilyRelationship' },
  'FAM_DIRECTA_ESTATUS':               { equiv: 'usStatus'          },

  // ── Pareja ──
  'PAREJA_NOMBRE':                     { clean: 'text'              },
  'PAREJA_APELLIDO':                   { clean: 'text'              },
  'PAREJA_NACIONALIDAD':               { equiv: 'countries'         },
  'PAREJA_MES':                        { equiv: 'month'             },
  'PAREJA_CIUDAD':                     { clean: 'text'              },
  'PAREJA_PAIS':                       { equiv: 'paisRegion'        },

  // ── Trabajo actual ──
  'WET_PRESENT_NOBRE_LUGAR':           { clean: 'text'              },
  'WET_PRESENT_CALLE':                 { clean: 'text'              },
  'WET_PRESENT_CIUDAD':                { clean: 'text'              },
  'WET_PRESENT_ESTADO':                { clean: 'text'              },
  'WET_PRESENT_ZIP':                   { clean: 'zip'               },
  'WET_PRESENT_TEL':                   { clean: 'phone'             },
  'WET_PRESENT_INGRESO_MES':           { equiv: 'month'             },
  'WET_PRESENT_ACTIVIDADES':           { clean: 'text', translate: true },
  'WET_PRESENT_OCUPACION':             { equiv: 'occupation'        },

  // ── Trabajo anterior ──
  'WET_PREV_NOMBRE':                   { clean: 'text'              },
  'WET_PREV_CALLE':                    { clean: 'text'              },
  'WET_PREV_CIUDAD':                   { clean: 'text'              },
  'WET_PREV_ESTADO':                   { clean: 'text'              },
  'WET_PREV_ZIP':                      { clean: 'zip'               },
  'WET_PREV_PAIS':                     { equiv: 'countries'         },
  'WET_PREV_TEL':                      { clean: 'phone'             },
  'WET_PREV_PUESTO':                   { clean: 'text', translate: true },
  'WET_PREV_JEFE_NOMBRE':              { clean: 'text'              },
  'WET_PREV_JEFE_APELLIDO':            { clean: 'text'              },
  'WET_PREV_ING_MES':                  { equiv: 'month'             },
  'WET_PREV_SALIDA_MES':               { equiv: 'month'             },
  'WET_PREV_ACTIVIDADES':              { clean: 'text', translate: true },

  // ── Estudios ──
  'EST_NOMBRE_ESCUELA':                { clean: 'text'              },
  'EST_CALLE':                         { clean: 'text'              },
  'EST_CIUDAD':                        { clean: 'text'              },
  'EST_ESTADO':                        { clean: 'text'              },
  'EST_ZIP':                           { clean: 'zip'               },
  'EST_PAIS':                          { equiv: 'countries'         },
  'EST_CURSO':                         { clean: 'text', translate: true },
  'EST_ING_MES':                       { equiv: 'month'             },
  'EST_SALIDA_MES':                    { equiv: 'month'             },

  // ── Adicional ──
  'ADD_IDIOMA_1':                      { equiv: 'language'          },
  'ADD_IDIOMA_2':                      { equiv: 'language'          },
  'ADD_IDIOMA_3':                      { equiv: 'language'          },
  'ADD_PAIS_1':                        { equiv: 'countries'         },
  'ADD_PAIS_2':                        { equiv: 'countries'         },
  'ADD_PAIS_3':                        { equiv: 'countries'         },
};


// ── processField ─────────────────────────────────────────
//  Aplica la regla correspondiente a un campo PDF.
//  Normaliza el valor antes de buscar en tablas de equiv
//  para tolerar acentos y variaciones menores del PDF.

function processField(pdfKey, value) {
  if (!value || value.trim() === '') return value;

  const rule = FIELD_RULES[pdfKey];
  if (!rule) return value;

  // Sin transformación
  if (rule.raw) return value.trim();

  // Limpieza de texto
  if (rule.clean && rule.clean !== 'visa') {
    const cleaned = CLEAN[rule.clean](value);
    // Los campos con translate se procesan en popup.js después
    return cleaned;
  }

  if (rule.clean === 'visa') return CLEAN.visa(value);

  // Equivalencia — normaliza para tolerancia de acentos
  if (rule.equiv) {
    const map = EQUIV[rule.equiv];
    const normalized = (value || '')
      .trim()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^\x00-\x7F]/g, '')
      .toUpperCase()
      .replace(/\s+/g, ' ')
      .trim();

    // Buscar por valor normalizado primero, luego por valor original
    const byNormalized = Object.entries(map).find(([k]) => {
      const kn = k.normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^\x00-\x7F]/g, '')
        .toUpperCase()
        .replace(/\s+/g, ' ')
        .trim();
      return kn === normalized;
    });

    if (byNormalized) return byNormalized[1];

    // Fallback directo
    const direct = map[value.trim()];
    if (direct) return direct;

    console.warn(`[VP] Sin equivalencia en "${rule.equiv}" para: "${value}"`);
    return value;
  }

  return value;
}


// ── getTranslatableFields ────────────────────────────────
//  Devuelve un objeto { pdfKey: valorLimpio } solo con los
//  campos marcados como translate:true y que tengan valor.

function getTranslatableFields(rawFields) {
  const result = {};
  for (const [key, rule] of Object.entries(FIELD_RULES)) {
    if (!rule.translate) continue;
    const val = (rawFields[key] || '').trim();
    if (!val) continue;
    result[key] = val;
  }
  return result;
}
